aws_snowflake_dbt_project:
  outputs:
    dev:
      account: VHJARJI-TR25167
      database: AIRBNB_2
      password: Yeswanthgiduturi@2401
      role: ACCOUNTADMIN
      schema: DBT_SCHEMA
      threads: 1
      type: snowflake
      user: YESWANTHGIDUTURI
      warehouse: COMPUTE_WH
  target: dev